# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - assistentedamsep

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: 'Create .env file'
        shell: bash
        run: |
          echo "NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}" > .env
          echo "NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}" >> .env
          echo "NEXTAUTH_URL=${NEXT_PUBLIC_URL}" >> .env
          echo "NEXTAUTH_SECRET=${NEXTAUTH_SECRET}" >> .env
          echo "NEXT_PUBLIC_FEEDBACK_FORM_URL=${NEXT_PUBLIC_FEEDBACK_FORM_URL}" >> .env
          echo "NEXT_PUBLIC_BUG_REPORT_FORM_URL=${NEXT_PUBLIC_BUG_REPORT_FORM_URL}" >> .env
          echo "NEXT_PUBLIC_DEBUG_AUTH=${NEXT_PUBLIC_DEBUG_AUTH}" >> .env
          echo "NODE_ENV=production" >> .env
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_URL: ${{ secrets.NEXT_PUBLIC_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXT_PUBLIC_FEEDBACK_FORM_URL: ${{ secrets.NEXT_PUBLIC_FEEDBACK_FORM_URL }}
          NEXT_PUBLIC_BUG_REPORT_FORM_URL: ${{ secrets.NEXT_PUBLIC_BUG_REPORT_FORM_URL }}
          NEXT_PUBLIC_DEBUG_AUTH: ${{ secrets.NEXT_PUBLIC_DEBUG_AUTH }}

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm install --force
          npm run build
      
      - name: Prepare Standalone Artifact
        run: |
          # O standalone precisa das pastas public e static manualmente
          cp -r public .next/standalone/public
          cp -r .next/static .next/standalone/.next/static

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .next/standalone

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8586252E5AD24248898D03041D501597 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9BA15C7C06CC434AA02918373E29AD23 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A55C702EF01943B5922765F5E7B740ED }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'assistentedamsep'
          slot-name: 'Production'
          package: .
          startup-command: "node server.js"
          
